"""cvr_osc_lib - A library for sending and receiving OSC messages for CVR."""
from cvr_osc_lib.osc_interface import OscInterface
from cvr_osc_lib.osc_messages_data import (
    AvatarChangeReceive,
    AvatarChangeSend,
    AvatarParameterChange,
    Input,
    InputName,
    PropAvailability,
    PropCreateReceive,
    PropCreateSend,
    PropDelete,
    PropLocation,
    PropLocationSub,
    PropParameter,
    TrackingDeviceData,
    TrackingDeviceStatus,
    TrackingPlaySpaceData,
    TrackingViveTrackerName,
    Vector3,
)

__all__ = [
    'OscInterface',
    'AvatarChangeReceive',
    'AvatarChangeSend',
    'AvatarParameterChange',
    'Input',
    'InputName',
    'PropAvailability',
    'PropCreateReceive',
    'PropCreateSend',
    'PropDelete',
    'PropLocation',
    'PropLocationSub',
    'PropParameter',
    'TrackingDeviceData',
    'TrackingDeviceStatus',
    'TrackingPlaySpaceData',
    'TrackingViveTrackerName',
    'Vector3',
]
